import "./globals.css";
import { Roboto, Lora, Poppins, Montserrat, Open_Sans } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-roboto" });
const lora = Lora({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-lora" });
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-poppins" });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-montserrat" });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-opensans" });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} ${lora.variable} ${poppins.variable} ${montserrat.variable} ${openSans.variable}`} suppressHydrationWarning>
      <body
        className="antialiased dark"

      >
        {children}
      </body>
    </html>
  );
}





